// ================================================================================== //
// THIS FILE IS AUTO-GENERATED
// ALL CHANGES WILL BE LOST
// ================================================================================== //
// SEE Cockpit/Scripts/devices.lua for the origin
#pragma once

enum Devices
{
    DEVICES_ENGINE = 20,
    DEVICES_AVIONICS = 2,
    DEVICES_RADAR = 10,
    DEVICES_SPOILERS = 16,
    DEVICES_AFCS = 27,
    DEVICES_EXT_LIGHTS = 25,
    DEVICES_AIRBRAKES = 13,
    DEVICES_TEMP2 = 41,
    DEVICES_NAV_TERRAIN = 24,
    DEVICES_HUFFER = 18,
    DEVICES_WEAPON_SYSTEM = 6,
    DEVICES_GEAR = 15,
    DEVICES_ILS = 1,
    DEVICES_CANOPY = 17,
    DEVICES_TEMP1 = 40,
    DEVICES_NVG = 35,
    DEVICES_NAV = 23,
    DEVICES_RWR = 31,
    DEVICES_ADI_AJB3A = 38,
    DEVICES_NVG_CONTROLS = 39,
    DEVICES_TEMP4 = 43,
    DEVICES_MCL = 37,
    DEVICES_TRIM = 26,
    DEVICES_INTERCOM_GUARD = 47,
    DEVICES_UHF_RADIO = 5,
    DEVICES_INTERCOM = 4,
    DEVICES_UHF_RADIO_GUARD = 46,
    DEVICES_COUNTERMEASURES = 32,
    DEVICES_TEMP5 = 44,
    DEVICES_SLATS = 12,
    DEVICES_TEMP3 = 42,
    DEVICES_ELECTRIC_SYSTEM = 3,
    DEVICES_TACAN = 48,
    DEVICES_SHRIKE = 33,
    DEVICES_RADIO = 28,
    DEVICES_BYPASS_FAN = 21,
    DEVICES_EFM_DATA_BUS = 36,
    DEVICES_SEAT = 45,
    DEVICES_EXTANIM = 11,
    DEVICES_RADARWARN = 19,
    DEVICES_ADI = 9,
    DEVICES_GUNSIGHT = 22,
    DEVICES_OXYGEN = 29,
    DEVICES_FLAPS = 14,
    DEVICES_SOUNDSYSTEM = 34,
    DEVICES_HYDRAULIC_SYSTEM = 7,
    DEVICES_HUD = 30,
    DEVICES_CLOCK = 8
};
